### ISSUE TITLE
Omni for Gedit

### ISSUE THREAD

**Issue by heyloh** [getomni/omni#16]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template);
- [x] The theme follows the Omni Color Palette;
- [x] The branch name is `main` (we will keep this name pattern from now on);
- [x] The theme has correct instructions on how to install it;
- [x] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Gedit
**Application URL:** https://wiki.gnome.org/Apps/Gedit
**GitHub URL:** https://github.com/heyloh/gedit

**Comment by jpedroschmitz** [comment]
Hey @heyloh! Thanks for creating another theme; it looks great. 💜 

We can include the theme in the organization. 🎉 
Since you are a member of the org, you can transfer your repository!

Just make sure to open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻 
Also, after the transfer, make sure to change all URLs to match the new repository link.

**Comment by heyloh** [comment]
Instructions followed! 🚀

**Comment by jpedroschmitz** [comment]
Great job, @heyloh. 💜

Don't forget to share it on social media, forums, and communities!
