### ISSUE TITLE
Omni for Terminal.app

### ISSUE THREAD

**Issue by demartini** [getomni/omni#25]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [X] The theme follows the [template](https://github.com/getomni/template);
- [X] The theme follows the Omni Color Palette;
- [X] The branch name is `main` (we will keep this name pattern from now on);
- [X] The theme has correct instructions on how to install it;
- [X] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Terminal.app
**Application URL:** https://en.wikipedia.org/wiki/Terminal_(macOS)
**GitHub URL:** https://github.com/demartini/terminal

**Comment by jpedroschmitz** [comment]
Wow, another awesome theme. Thanks @demartini 💜 

We can include the theme in the organization. 🎉 
Since you already are a member of the org, you can transfer your repository!

Just make sure to open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻 
Also, after the transfer, make sure to change all URLs to match the new repository link.

If you want, open a PR with all the new themes (you don't need to create 3 separate PR's).

**Comment by demartini** [comment]
Hey @jpedroschmitz we need to create the Terminal.app team so I can finish the transfer.

**Comment by jpedroschmitz** [comment]
Sorry, I forgot to do so :/

I created the team!

**Comment by demartini** [comment]
No problem! :laughing:

I just finished the transfer and PR #27 opened.

> Please leave the actions enabled so that we can release the new versions when the source code is changed.

**Comment by jpedroschmitz** [comment]
Thanks for creating all these themes @demartini! 🚀
