### ISSUE TITLE
Omni for Slack

### ISSUE THREAD

**Issue by demartini** [getomni/omni#30]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [X] The theme follows the [template](https://github.com/getomni/template);
- [X] The theme follows the Omni Color Palette;
- [X] The branch name is `main` (we will keep this name pattern from now on);
- [X] The theme has correct instructions on how to install it;
- [X] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Slack
**Application URL:** https://slack.com
**GitHub URL:** E.g. https://github.com/demartini/slack

**Comment by jpedroschmitz** [comment]
Hey @demartini, thanks for porting Omni to Slack @demartini 💜 

We can include the theme in the organization. 🎉 
Since you already are a member of the org, you can transfer your repository!

Just make sure to open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻 
Also, after the transfer, make sure to change all URLs to match the new repository link.

**Comment by demartini** [comment]
Hey @jpedroschmitz, I finished the transfer and PR #31 opened.

**Comment by jpedroschmitz** [comment]
Thanks for creating another theme. Everything looks fine! 💜
